# Generated by Django 5.0.1 on 2024-04-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_app', '0002_alter_trackin_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackin',
            name='value',
            field=models.FloatField(),
        ),
    ]
